# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
# Custom vars
version: 2.1.0

profile_image: "/assets/images/vesikalık.jpg"
github_url: "https://github.com/erenyildiz33"


# Setup
title: Eren Yildiz, Ph.D.
tagline: ''
description: 'Post Doc. at GA Tech.'
url: http://erenyildiz33.github.io
baseurl: "/"

author:
  name: 'Eren Yildiz'
  url: #https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

#theme: jekyll-theme-hyde
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-gist
  - jekyll-paginate
  #- jekyll-github-metadata

