# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Hyde
tagline: 'A Jekyll theme'
description: 'A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content.'
url: http://erenyildiz33.github.io
baseurl: "/"

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

#theme: jekyll-theme-hyde
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-github-metadata

