# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Eren Yildiz, Ph.D
tagline: ''
description: 'Post doctoral researcher aat Georgia Isntitute of Technology.'
url: http://erenyildiz33.github.io
baseurl: "/"

author:
  name: 'Eren Yildiz'
  url: #https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

#theme: jekyll-theme-hyde
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-github-metadata

